// Public surface for @polygonlabs/example-client.
//
// Everything in `./generated/` is regenerated by `pnpm run generate`
// from the registered Zod schemas in `@polygonlabs/example-schemas`,
// so there is no rename layer to drift. The hand-written barrel below
// imports only from `./generated/index.js` — the auto-barrel that
// `@polygonlabs/zod-to-openapi-heyapi`'s `defineRegistryClientConfig`
// keeps complete:
//
//   - `client` for `client.setConfig({ baseUrl })` at app entry
//   - Every SDK wrapper (`getBlockNumber`, `createMessage`, …) —
//     codec-aware via the plugin's per-op transformer
//   - The `TransportError` / `ResponseValidationError` classes plus their
//     `is*Error` type-predicate guards for canonical narrowing
//   - `WrapErrors<TData, TError, ThrowOnError>` — the wrapper's
//     statically widened return type, surfaced for typed-error
//     narrowing demos in the frontend
//   - The `${Op}Transformer` / `${Op}InputTransformer` / `${Op}ErrorTransformer`
//     helpers (re-exported for completeness; most consumers won't
//     reach for these directly)
//
// React-flavoured TanStack Query options factories
// (`getBlockMetadataOptions`, `getBlockNumberOptions`, etc.) and the
// `${Op}Mutation` factories live in the `./react` subpath export so
// consumers that don't need React don't pay the @tanstack/react-query
// peer-dep cost.
//
// For advanced setups that need more than the singleton client —
// multiple instances pointing at different base URLs, per-request
// config in SSR, a custom fetch adapter — import `createClient` and
// `createConfig` from the `./factory` subpath:
//
//   import { createClient, createConfig } from '@polygonlabs/example-client/factory';
//   const myClient = createClient(createConfig({ baseUrl, fetch: customFetch }));
//   await getBlockNumber({ client: myClient });
export {
  client,
  createMessage,
  type CreateMessageError,
  type CreateMessageInput,
  type CreateMessageResponse,
  getBlockMetadata,
  type GetBlockMetadataError,
  type GetBlockMetadataInput,
  type GetBlockMetadataResponse,
  getBlockNumber,
  type GetBlockNumberResponse,
  getHealthCheck,
  type GetHealthCheckResponse,
  getHello,
  type GetHelloResponse,
  getMessage,
  type GetMessageError,
  type GetMessageResponse,
  getWidget,
  type GetWidgetError,
  type GetWidgetResponse,
  isResponseValidationError,
  isTransportError,
  isWrapperError,
  listEvents,
  type ListEventsInput,
  type ListEventsResponse,
  listMessages,
  type ListMessagesInput,
  type ListMessagesResponse,
  ResponseValidationError,
  TransportError,
  type WrapErrors
} from './generated/index.js';
