// Public surface for @polygonlabs/example-client.
//
// Consumers import:
//   - `client` to set the baseUrl (and any other fetch options) once at
//     application entry: `client.setConfig({ baseUrl })`.
//   - The named SDK functions (`getHealthCheck`, `getHello`, `getBlockNumber`)
//     to make typed calls against the configured baseUrl.
//
// The generated SDK is the source of truth for response types and runtime
// behaviour; everything in `./generated/` is regenerated by `pnpm run
// generate` from the registered Zod schemas in `@polygonlabs/example-schemas`,
// so there is no rename layer to drift.
//
// React-flavoured TanStack Query options factories (`getBlockNumberOptions`
// etc.) live in the `./react` subpath export so consumers that don't need
// React don't pay the @tanstack/react-query peer-dep cost.
export { client } from './generated/client.gen.ts';
export { getBlockNumber, getHealthCheck, getHello } from './generated/sdk.gen.ts';
