// TanStack Query options factories generated by hey-api's @tanstack/react-query
// plugin. Usage:
//
//   import { getBlockNumberOptions } from '@polygonlabs/example-client/react';
//   const { data } = useQuery(getBlockNumberOptions());
//
// Configure the baseUrl once at application entry via the singleton client
// from the main entrypoint:
//
//   import { client } from '@polygonlabs/example-client';
//   client.setConfig({ baseUrl: env.VITE_API_URL });
export {
  getBlockNumberOptions,
  getBlockNumberQueryKey,
  getHealthCheckOptions,
  getHealthCheckQueryKey,
  getHelloOptions,
  getHelloQueryKey
} from './generated/@tanstack/react-query.gen.ts';
