name: Changeset check

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  check:
    uses: 0xPolygon/apps-team-workflows/.github/workflows/changeset-check.yml@main
    secrets: inherit
