name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write # required for npm OIDC trusted publishing

jobs:
  release:
    uses: 0xPolygon/apps-team-ops/.github/workflows/release.yml@main
    secrets: inherit
